### ISSUE TITLE
Rename the attributes in the FIFOBus interface

### ISSUE THREAD

**Issue by cfelton** [cfelton/rhea#10]
The attributes (Signals) in the [`FIFOBus`](https://github.com/cfelton/rhea/blob/master/rhea/system/stream/fifobus.py#L20) interface originally used abbreviations.  Modify the attributes to use the full word.

Example,

```python
self.write = ...
self.writedata = ...
self.read = ...
self.readdata = ...
```

**Comment by forumulator** [comment]
Pull request issued for cfelton:master from forumulator:fifoattrib with the changes.
