### ISSUE TITLE
Long simulation tests

### ISSUE THREAD

**Issue by cfelton** [cfelton/rhea#17]
Some of the tests in the test suite take considerable time to execute. To manage the long simulations in the test suite the long tests should be marked.  This change should mark the long running "full" tests as ~~`long_test`~~ `skip_long_sim_test`.  The pytest package has a mechanism to mark certain test and select when these are run.  The "long" tests will not be run normally but they can be run manually for additional test coverage or run only with pypy in travis.

Currently, many of these tests are skipped (`pytest.mark.skip(True)`).  These are the tests that need to be dealt with.

**Comment by forumulator** [comment]
Created a pull request ( #20 ) initially marking the slowest tests.

**Comment by cfelton** [comment]
Thanks for the PR!  I realize I mentioned `long_test` in the description but as discussed in #20 a longer name (short-hand for the pytest descriptor) is preferred.  Thanks for updating the PR to reflect the more descriptive name.
