### ISSUE TITLE
Vivido 2016.2 and ISE 14.7 can't process generated .tcl files with absolute paths or spaces on windows 10

### ISSUE THREAD

**Issue by NickShaffner** [cfelton/rhea#41]
Generated a simple switches to leds program for zybo, and the following bit of the flow:

>  vivado -mode batch -source Z:\Dropbox\Projects\PU\build\pu.tcl

resulted in the following output:

`# add_files Z:\Dropbox\Projects\PU\build\pu.v
ERROR: [Vivado 12-172] File or Directory 'Z:DropboxProjectsPuildpu.v' does not exist`

The offending line of the TCL file:

`
add_files Z:\Dropbox\Projects\PU\build\pu.v
`

The same issue happens for all other paths in the file, and is corrected by changing the paths to forward slashes.  (Which the vivido gui seems to do in it's own 'choose a file' dialogs).

Fix incoming shortly.

**Comment by cfelton** [comment]
Thanks for tackling this issue in your current PR!

**Comment by NickShaffner** [comment]
Instead of changing these to forward slashes as vivado does, I opted to escape the backslashes - so I don't end up 'second guessing' the os.path.join black box.

**Comment by NickShaffner** [comment]
This should be fixed with https://github.com/cfelton/rhea/pull/40 but should also be double checked for the other tools (eg ISE)

**Comment by NickShaffner** [comment]
Reopening because this is also the case for ISE (14.7) - fix incoming.

**Comment by NickShaffner** [comment]
https://github.com/cfelton/rhea/pull/52 fixes this for ISE 14.7 on Windows 10

**Comment by NickShaffner** [comment]
https://github.com/cfelton/rhea/pull/52 fixes this for ISE 14.7 on Windows 10

**Comment by NickShaffner** [comment]
ISE side of this merged with https://github.com/cfelton/rhea/pull/52
